language: python
fast_finish: true
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3
env:
  - RQ_VERSION="rq==1.3"
  - RQ_VERSION="rq==1.2"
  - RQ_VERSION="rq==1.1"
  - RQ_VERSION="rq==1.0"
  - RQ_VERSION="-e git+https://github.com/rq/rq#egg=rq"

install:
  - "bash -c '[[ $(python -V) == \"Python 3.4.\"* ]] && pip install setuptools==24.0.3 || :'"
  - "pip install -r requirements.txt"
  - "pip install $RQ_VERSION"
  - "pip install flake8 pytest"
script:
  - pytest
  - "flake8 rq_dashboard tests"
services:
  - redis-server
